---
- name: Start Oracle DB
  hosts: oracle
  gather_facts: no
  vars:
    #variable for Start DB
    oracle_sid: "cdb1"
    oracle_base: "/u01/app/oracle"
    oracle_home: "/u01/app/oracle/product/19.3.0/db100"
    oracle_group: oinstall
    oracle_user: oracle
    oracle_stage: "/u01/stage/"
    env:
      ORACLE_HOME: "{{ oracle_home }}"
      ORACLE_BASE: "{{ oracle_base }}"
      ORACLE_SID: "{{ oracle_sid }}"
      #TNS_ADMIN: "{{ tns_admin }}"
      PATH: "{{ oracle_home }}/bin:{{ oracle_home }}/OPatch:$PATH:/bin:/usr/bin::/usr/ccs/bin"
  tasks:
     - name: Run check_status.sql
       become: yes
       become_user: "{{ oracle_user }}"
       shell: |
         echo exit | sqlplus / as sysdba @{{ oracle_stage }}/check_status.sql
       register: status_result
       environment: "{{ env }}"
       tags: check_status
         
     - debug: var=status_result.stdout_lines
       tags: check_status
       
     - name: Start Oracle DB
       become: yes
       become_user: "{{ oracle_user }}"
       shell: |
         echo 'startup;' | sqlplus / as sysdba
       environment: "{{ env }}"
       register: startdb_output
       when: "'OPEN' not in status_result.stdout_lines"
       tags:
         - startdb
       
     - debug: var=startdb_output.stdout_lines
       when: "'OPEN' not in status_result.stdout_lines"
